import type { Metadata } from "next";
import { Inter, Roboto, Lora } from 'next/font/google'
import "../styles/styles.scss";
import Navbar from "./modules/lib/components/navbar/Navbar";
import Footer from "./modules/lib/components/footer/Footer";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  display: 'swap',
  weight: ['100', '300', '400', '500', '700', '900']
});

const lora = Lora({
  subsets: ['latin'],
  variable: '--font-lora',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${roboto.variable} ${lora.variable}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
